name: Mastodon Benchmark
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  docker-build:
    name: Build with Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init mastodon

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v4
        with:
          context: ./mastodon
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  nscloud-build:
    name: Build with Namespace
    runs-on: nscloud-ubuntu-22.04-staging-amd64-4x8
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init mastodon

      - uses: namespacelabs/nscloud-setup@v0

      - uses: namespacelabs/nscloud-setup-buildx-action@v0

      - uses: docker/build-push-action@v4
        with:
          context: ./mastodon
          platforms: linux/amd64,linux/arm64
